server:
  port: 9999

spring:
  datasource:
    username: root
    password: 20040308Yingtong
    url: jdbc:mysql:///user_management_system
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.lantu: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1